apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    env: dev
    dc: IN
  type: NodePort
  ports:
  - nodePort: {{ .Values.grafanaPort }}
    port: 3000