apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  #nfs:
    #server: "{{ .Values.grafanaNFS }}"
    #path: "/"
  hostPath:
    path: "/mnt/sda1/data/grafana"