apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  #nfs:
    #server: "{{ .Values.prometheusNFS }}"
    #path: "/"
  hostPath:
    path: "/mnt/sda1/data/grafana"